export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_PRODUCT_QTY = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT_QTY = 'DECREMENT_PRODUCT';
export const CHANGE_PRODUCT_QTY = 'CHANGE_PRODUCT_QTY';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
